[project]
name = "rmh-data-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dcm2niix>=1.0.20241211",
    "nnunetv2>=2.0",
    "pandas>=2.0.3",
    "pydicom>=2.4.4",
    "torch<=2.5",
]
